// src/lexer/TokenType.java
package lexer;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, COLON, EQUAL, QUOTE, COMMA,
    KUROMI, START, CLOSE, GAME, LOAD_IMAGE, DISPLAY_IMAGE, SHOW_TEXT, PLAY_SOUND,
    DRAW_RECTANGLE, DRAW_CIRCLE, DRAW_LINE, DRAW_TRIANGLE, PRINT, LET, REPEAT, TIMES, WAIT,
    IF, THEN, ELSE, CALL,
    IDENTIFIER, STRING, NUMBER,
    CENTERED, LEFT, RIGHT,
    EOF
}